name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24.0.1'

      - name: R setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # - name: Reconfigure Java
      #   run: R CMD javareconf

      - name: Install system deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

