name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24.0.1'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # - name: Reconfigure Java
      #  run: R CMD javareconf

      - name: Install deps (incl covr)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run covr::codecov()
        run: |
          Rscript -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

